<?php
/**
 * Message translations.
 *
 * This file is automatically generated by "yii message/extract" command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of "@@" marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return
    [
        '{n, plural, other{cucumber}}'=> '{n, plural, =1{Редактировать} other{Обновить}}',

        "Show «{attribute}»" => "Показать «{attribute}»",
        "Show «{attribute}» #{item}"  => "Показать «{attribute}» #{item}",

        "Open «{attribute}»" => "Открыть «{attribute}»",
        "Edit «{attribute}»" => "Изменить «{attribute}»",
        "Create «{attribute}»" => "Создать «{attribute}»",
        "Add «{attribute}»" => "Добавить «{attribute}»",
        "Copy «{attribute}»" => "Копировать «{attribute}»",
        "Delete «{attribute}»" => "Удалить «{attribute}»",
        "Editing of {attribute}" => "Редактирование {attribute}",
        "Editing of «{attribute}»" => "Редактирование «{attribute}»",
        "View of {attribute}" => "Просмотр {attribute}",
        "View of «{attribute}»" => "Просмотр «{attribute}»",
//        'cucumber' => '{0, Редактировать|Обновить}',
        "Adding data" => "Добавление",
        "Adding data of «{attribute}»" => "Добавление «{attribute}»",
        "Adding of «{attribute}»" => "Добавление «{attribute}»",
        "Adding of {attribute}" => "Добавление {attribute}",


        "from" => "от",
        "ID From" => "От ID",
        "ID Till" => "До ID",

        "Created at from" => "Добавлено От",
        "Created at till" => "Добавлено До",
        "Updated at from" => "Обновлено От",
        "Updated at till" => "Обновлено До",
        "Decline at from" => "Заблокировано От",
        "Decline at till" => "Заблокировано До",
        "Search by parameters" => "Поиск по параметрам",

        "Delete of «{attribute}» #{item}"          => "Удаление «{attribute}» #{item}",


        "Created: {attribute}" => "Создан: {attribute}",
        "Creating {attribute}" => "Создание {attribute}",

        "Update"                                    => "Обновить",
        "Search"                                    => "Искать",
        "Reset"                                     => "Сбросить",
        "Contact us"                                => "Контакты",
        "Log in"                                    => "Войти",
        "Entrance"                                  => "Войти",
        "log in"                                    => "Авторизоваться",
        "Log out ({username})"                      => "Выход ({username})",
        "Sign In" => "Авторизоваться",
        "Log out" => "Выход",
        "You may login with: <strong>admin/admin</strong> or <strong>demo/demo</strong>" => "Для входа используйте: <strong>admin/admin</strong> или <strong>demo/demo</strong>",

        "Remember me"           => "Запомнить меня",
        "Login"                 => "Логин",
        "Password"              => "Пароль",
        "Incorrect password."   => "Некорректный пароль.",
        "Incorrect username or password." => "Некорректный логин или пароль.",
        "New password has been changed." => "Новый пароль был изменен.",


        "Wage"                  => "Заработная плата",
        "When processing your request an error occurred."        => "При обработки вашего запроса произошла ошибка.",

        "The data is saved"             => "Данные сохранены",
        "The data is delete"             => "Данные удалены",
        "The data is not saved"         => "Данные не сохранены",
        "The data is not delete"         => "Данные не сохранены",
        "Successful"                    => "Успешно",
        "Unsuccessful"                  => "Неудачно",

        "Name"       => "Название",
        "First Name"       => "Имя",
        "Last Name"       => "Фамилия",
        "Patronymic"       => "Отчество",
        "Gender"       => "Пол",
        "Comment"                                   => "Комментарии",
        "Created By"                                => "Добавил",
        "Created At"                                => "Добавлено",
        "Updated By"                                => "Обновил",
        "Updated At"                                => "Обновлено",

        "Failed to remove «{attribute}»"            => "Ошибка удаления «{attribute}»",
        "Failed to save «{attribute}»"              => "Ошибка сохранения «{attribute}»",
        "Failed to selection «{attribute}»"         => "Ошибка выбора «{attribute}»",
        "Error due to duplicate item"               => "Ошибка из-за дубликата элементов",
        "«{attribute}» is not implemented."         => "«{attribute}» не будет реализован.",
        "Role of user"                              => "Роль пользователя",
        "role of user"                              => "Роли пользователя",
        "Roles of user"                             => "Ролей пользователя",
        "The User"                                  => "Пользователя",
        "user"                                      => "Пользователя",
        "Authorization"         => "Авторизация",
        "Home"         => "Главная страница",
        "Staff data"         => "Данные персонала",
        "Employees"         => "Сотрудники",
        "Employee"         => "Сотрудник",
        "employee"         => "Сотрудника",
        "Departments"         => "Отделы",
        "Department"         => "Отдел",
        "department"         => "Отдела",
        "communication with departments"         => "связь с отделам",

        "Test"         => "Тестовое задание",
        "Select at least one department"         => "Выберите хотя бы один отдел",
        "This «{attribute}» has been added"                        =>  "Этот «{attribute}» уже был добавлен",
        "this «{attribute}» has been added"                        =>  "Эти «{attribute}» уже были добавлены",

        "Female"             => "Женский",
        "Male"             => "Мужской",
        "Number of employees"             => "Кол-во сотрудников",
        "Max wage"             => "Max зарплата",

        "Create a «{attribute}»"                 => "Создать «{attribute}»",
        "Change a «{attribute}»"                 => "Изменить «{attribute}»",
        "It is forbidden to remove a department with employees"                 => "Запрещено удалять отдел с сотрудниками",
        "Full name"       => "ФИО",
        "Relation of employees with departments"       => "Связь сотрудников с отделами",
        "It is necessary to add data of employees and departments."       => "Необходимо добавить данные сотрудников и отделов",

    ];